from django.urls import path
from .import views

urlpatterns = [
    path('', views.index, name='index'),
    path('registration',views.registration,name='registration'),
    path('login_view',views.login_view,name='login_view'),
    path('hostel_admin_view',views.hostel_admin_view,name='hostel_admin_view'),
    path('student_list_view',views.student_list_view,name='student_list_view'),
    path('logout_view',views.logout_view,name='logout_view'),
    path('delete_student/<int:student_id>/',views.delete_student,name='delete_student'),
    path('edit_student/<int:student_id>/',views.edit_student,name='edit_student'),
    # path('warden_details_view',views.warden_details_view,name='warden_details_view'),
    # path('warden_registration_view',views.warden_registration_view,name='warden_registration_view'),
    # path('warden_list_view',views.warden_list_view,name='warden_list_view'),
    path('upload_images',views.upload_images,name='upload_images'),
    path('image_list_admin',views.image_list_admin,name='image_list_admin'),
    path('announcement_create_view',views.announcement_create_view,name='announcement_create_view'),
    path('announcement_list_view',views.announcement_list_view,name='announcement_list_view'),
    path('gallery_view',views.gallery_view,name='gallery_view'),
    path('room_status_view',views.room_status_view,name='room_status_view'),
    path('about_view',views.about_view,name='about_view'),
    path('gallery_main_view',views.gallery_main_view,name='gallery_main_view'),
    path('contact_view',views.contact_view,name='contact_view'),
    path('hostel_student_view',views.hostel_student_view,name='hostel_student_view'),
    path('student_profile',views.student_profile,name='student_profile'),
    path("student_complaints/", views.student_complaints, name="student_complaints"),
    path("admin_complaints/", views.admin_complaints, name="admin_complaints"),
    path("reply_complaint/<int:id>/", views.reply_complaint, name="reply_complaint"),
    path('request_cleaning',views.request_cleaning,name='request_cleaning'),
    path('request_maintenance',views.request_maintenance,name='request_maintenance'),
    path('mess_menu',views.mess_menu,name='mess_menu'),
    path('student_announcement_list_view',views.student_announcement_list_view,name='student_announcement_list_view'),
    path('update_images/<int:i_id>/', views.update_images, name='update_images'),
    path('delete_images/<int:i_id>/', views.delete_images, name='delete_images'),
    path('update_announcements/<int:i_id>/', views.update_announcements, name='update_announcements'),
    path('delete_announcements/<int:i_id>/', views.delete_announcements, name='delete_announcements'),
]