# Generated by Django 5.2.7 on 2025-11-02 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hostel_Manager_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint_tab',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
